generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 peanut
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        title: Permission list
        display: [=name, description, created_at, updated_at]

      filter:
        display:              [name, users_list, groups_list]
        
      edit:
        title: Editing Permission "%%name%%"

      new:
        title: New Permission

      form:
        display:
          "General":      [name]
          "Content":      [description]
          "Informations": [groups_list, users_list]