# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport:      width=device-width, initial-scale=1.0

  stylesheets:
    - /peanutAssetPlugin/css/admin.css?v=2:              { media: 'screen, projection' }
    - http://fonts.googleapis.com/css?family=Oswald:     { media: 'screen, project' }
    - /peanutAssetPlugin/css/handheld.css?v=2:           { media: 'handheld' } 
    - jquery-ui-1.8.16.custom.css:                       {media: 'screen, projection' }
    - /css/admin.css:                                    {media: 'screen, projection' }

  javascripts:     [ social.js, jquery-ui-1.8.16.custom.min.js, /peanutAssetPlugin/js/admin.js, /peanutAssetPlugin/js/jquery.tipTip.minified.js, general.js ]
    

  has_layout:      true
  layout:          layout