<?php

/**
 * peanutSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutSettings');
    }
}