generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 peanut
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Password (again)" }

      list:
        title:                User list
        display:              [=username, created_at, updated_at, last_login]

      filter:
        display:              [username, groups_list, permissions_list, is_active]

      form:
        class: sfGuardUserAdminForm
        display:
          "General":          [username, email_address]
          "Content":          [first_name, last_name, password, password_again]
          "Informations":     [is_active, groups_list, permissions_list]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User