<?php

/**
 * sfGuardGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupPermissionTable extends PluginsfGuardGroupPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroupPermission');
    }
    
    /*
     * Get all permission
     * 
     * @return  object  $p
     */
    public function getAllPermissions()
    {
      $p = $this->createQuery('p');
      return $p;
    }
    
    /*
     * Get all permissions with the group
     * 
     * @param    group id   $id     
     * 
     * @return   object  $p
     */
    public function getGroupPermissions($id)
    {
      $p = $this->getAllPermissions()
                ->leftJoin('p.Group g')
                ->leftJoin('p.Permission x')
                ->addWhere('g.id = ?', $id);        
      return $p;
    }
    
    /*
     * Get all group permissions
     * 
     * @return   object  $p
     */
    public function getGroupsPermissions()
    {
      $p = $this->getAllPermissions()
                ->leftJoin('p.Group g')
                ->leftJoin('p.Permission x');
      return $p;
    }
}