<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroup');
    }
    
    /*
     * Get a permission
     * 
     * @return  object  $p
     */
    public function getGroup()
    {
      $p = $this->createQuery('p');
      return $p;
    }
    
    /*
     * Get all permissions
     * 
     * @return   object  $p
     */
    public function getGroups()
    {
      $p = $this->getGroup();        
      return $p;
    }
}