<?php

/**
 * sfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }
    
    /*
     * Get a permission
     * 
     * @return  object  $p
     */
    public function getPermission()
    {
      $p = $this->createQuery('p');
      return $p;
    }
    
    /*
     * Get all permissions
     * 
     * @return   object  $p
     */
    public function getPermissions()
    {
      $p = $this->getPermission();        
      return $p;
    }
}