<?php

/**
 * peanutItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpeanutItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object peanutItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('peanutItem');
  }

  /**
   * Retrieves item object.
   *
   * @param  string|int $item     The id or slug of item
   *
   * @return peanutItem
   */
  public function getItem($item, $type = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->where('p.id = ?', $item)
            ->orWhere('p.slug = ?', $item)
            ->orderBy('p.position ASC');

    if(null !== $type)
    {
      $p->addWhere('p.type = ?', $null);
    }
    
    return $p;
  }

  /**
   * Retrieves items object.
   *
   * @param  string $type     The type of item
   *
   * @return peanutItem
   */
  public function getItems($type = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->orderBy('p.position ASC');

    if(null !== $type)
    {
      $p->addWhere('p.type = ?', $null);
    }

    return $p;
  }

  /**
   * Retrieves items object by menu.
   *
   * @param  string|int $menu     The id or slug of menu
   * @param  string $type            The type of item
   *
   * @return peanutItem
   */
  public function getItemsByMenu($menu, $type = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->where('m.id = ?', $menu)
            ->orWhere('m.slug = ?', $menu)
            ->orderBy('p.position ASC');

    if(null !== $type)
    {
      $p->addWhere('p.type = ?', $null);
    }
    
    return $p;
  }

  /**
   * Retrieves items object by user.
   *
   * @param  string|int $user     The id or username of user
   * @param  string $type         The type of item
   *
   * @return peanutItem
   */
  public function getItemsByUser($user, $type = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->where('s.id = ?', $user)
            ->orWhere('s.username = ?', $user)
            ->orderBy('p.position ASC');

    if(null !== $type)
    {
      $p->addWhere('p.type = ?', $null);
    }
    
    return $p;
  }

}