<?php

/**
 * PluginpeanutLinkRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpeanutLinkRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpeanutLinkRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpeanutLinkRelation');
    }
}