<?php

/**
 * peanutMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blackroom
 * @subpackage model
 * @author     Alexandre pocky Balmes
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginpeanutMenu extends BasepeanutMenu
{
}
