<?php

/**
 * PluginpeanutXFNTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpeanutXfnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpeanutXFNTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpeanutXfn');
    }
}