<?php

/**
 * PluginpeanutXFN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    peanutCorporatePlugin
 * @subpackage mode
 * @author     Alexandre "pocky" Balmes <albalmes@gmail.com> <albalmes@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginpeanutXfn extends BasepeanutXfn
{

}