<?php

/**
 * peanutPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutPageTable extends PluginpeanutPageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutPage');
    }
}