<?php

/**
 * peanutMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutMenuTable extends PluginpeanutMenuTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutMenu');
    }
}