<?php

/**
 * peanutItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutItemTable extends PluginpeanutItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutItem');
    }
}