<?php

/**
 * peanutLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutLinkTable extends PluginpeanutLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutLink');
    }
}