<?php

/**
 * peanutXfnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutXfnTable extends PluginpeanutXfnTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutXfnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutXfn');
    }
}