<?php

/**
 * peanutSeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class peanutSeoTable extends PluginpeanutSeoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object peanutSeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('peanutSeo');
    }
}